In [2]:
import warnings

warnings.simplefilter("ignore")
import numpy as np
import matplotlib.pyplot as plt
np.seterr(all="ignore")
from threeML import *
from astromodels import *
from astromodels.functions.function import Function1D, FunctionMeta

LMC1halfdeg_pha = "/home/jortecal/GitHub/eRosita/CookBook/srctoolout_000_SourceProducts_00001_1halfdeg_mask30/srctoolout_120_SourceSpec_00001.fits"
LMC1halfdeg_rmf = "/home/jortecal/GitHub/eRosita/CookBook/srctoolout_000_SourceProducts_00001_1halfdeg_mask30/srctoolout_120_RMF_00001.fits"
LMC1halfdeg_arf = "/home/jortecal/GitHub/eRosita/CookBook/srctoolout_000_SourceProducts_00001_1halfdeg_mask30/srctoolout_120_ARF_00001.fits"

20:58:46 INFO      Starting 3ML!                                                                     ]8;id=5595;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=159177;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/__init__.py#39\39]8;;\

         WARNING   WARNINGs here are NOT errors                                                      ]8;id=432683;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=71540;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/__init__.py#40\40]8;;\

         WARNING   but are inform you about optional packages that can be installed                  ]8;id=1152;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=133673;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/__init__.py#41\41]8;;\

         WARNING    to disable these messages, turn off start_warning in your config file            ]8;id=263658;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=677863;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/__init__.py#44\44]8;;\

20:58:46 WARNING   ROOT minimizer not available                                                ]8;id=749099;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=29171;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1345\1345]8;;\

         WARNING   Multinest minimizer not available                                           ]8;id=198462;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=778927;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1357\1357]8;;\

         WARNING   PyGMO is not available                                                      ]8;id=760901;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=945926;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1369\1369]8;;\

         WARNING   The cthreeML package is not installed. You will not be able to use plugins which  ]8;id=960417;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=660080;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/__init__.py#94\94]8;;\
                  require the C/C++ interface (currently HAWC)

         WARNING   Could not import plugin FermiLATLike.py. Do you have the relative instrument     ]8;id=78745;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=598034;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/__init__.py#144\144]8;;\
                  software installed and configured?

         WARNING   Could not import plugin HAWCLike.py. Do you have the relative instrument         ]8;id=229506;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=54489;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/__init__.py#144\144]8;;\
                  software installed and configured?

         WARNING   No fermitools installed                                              ]8;id=786903;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/utils/data_builders/fermi/lat_transient_builder.py\lat_transient_builder.py]8;;\:]8;id=553540;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/utils/data_builders/fermi/lat_transient_builder.py#44\44]8;;\

         WARNING   Env. variable OMP_NUM_THREADS is not set. Please set it to 1 for optimal         ]8;id=933896;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=570580;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/__init__.py#387\387]8;;\
                  performances in 3ML

         WARNING   Env. variable MKL_NUM_THREADS is not set. Please set it to 1 for optimal         ]8;id=697159;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=298056;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/__init__.py#387\387]8;;\
                  performances in 3ML

         WARNING   Env. variable NUMEXPR_NUM_THREADS is not set. Please set it to 1 for optimal     ]8;id=8127;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=840322;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/__init__.py#387\387]8;;\
                  performances in 3ML

In [ ]:
spectral_model1 =  TbAbs() * (APEC() + Powerlaw()) + APEC() 

###############################################################################################################################
# Inclusion of the particle background model FWC for TM1
########################################################################################################################################
import re

file_path = "/home/jortecal/Downloads/TM1_FWC_v1.0.dat"

with open(file_path, "r") as f:
    lines = f.readlines()

# Extract the model definition (first line)

# Extract parameter values from the remaining lines
parameters = []
for line in lines[1:]:
    if line.strip():  # Skip empty lines
        parameters.append([float(x) for x in re.split(r"\s+", line.strip())])


# Define the components of the model
constant = Constant()
gaussians = [Gaussian() for _ in range(14)]  # 14 Gaussian components
powerlaw1 = Powerlaw()
powerlaw2 = Powerlaw()

# Define the expfac component
class ExpFac(Function1D, metaclass=FunctionMeta):
    r"""
    description :
        Exponential modification of a spectrum.

        M(E) = 1 + A * exp(-f * E) for E > E_c
               1                   for E <= E_c

    parameters :
        A :
            desc : Amplitude of the exponential modification
            initial value : 1.0
            min : -100.0
            max : 100.0
            delta : 0.1
        f :
            desc : Exponential factor
            initial value : 1.0
            min : -100.0
            max : 100.0
            delta : 0.1
        E_c :
            desc : Start energy of the modification
            initial value : 1.0
            min : -100.0
            max : 100.0
            delta : 0.1
    """

    def _set_units(self, x_unit, y_unit):
        self.A.unit = y_unit
        self.f.unit = 1 / x_unit
        self.E_c.unit = x_unit

    def evaluate(self, x, A, f, E_c):
        return 1 + A * np.exp(-f * x) * (x > E_c)

# Define the bkn2pow component
class Bkn2Pow(Function1D, metaclass=FunctionMeta):
    r"""
    description :
        A three-segment broken power law.

        A(E) = K * E^(-Gamma_1) for E <= E_break1
               K * E_break1^(Gamma_2 - Gamma_1) * E^(-Gamma_2) for E_break1 < E <= E_break2
               K * E_break1^(Gamma_2 - Gamma_1) * E_break2^(Gamma_3 - Gamma_2) * E^(-Gamma_3) for E > E_break2

    parameters :
        K :
            desc : Normalization at 1 keV
            initial value : 1.0
            min : 1e-10
            max : 1e10
            delta : 0.1
        Gamma1 :
            desc : Photon index for E <= E_break1
            initial value : -1.5
            min : -10.0
            max : 10.0
            delta : 0.1
        E_break1 :
            desc : First break energy in keV
            initial value : 10.0
            min : 1e-20
            max : 1e3
            delta : 1.0
        Gamma2 :
            desc : Photon index for E_break1 < E <= E_break2
            initial value : -2.0
            min : -10.0
            max : 10.0
            delta : 0.1
        E_break2 :
            desc : Second break energy in keV
            initial value : 100.0
            min : 1e-20
            max : 1e4
            delta : 1.0
        Gamma3 :
            desc : Photon index for E > E_break2
            initial value : -2.5
            min : -10.0
            max : 10.0
            delta : 0.1
    """

    def _set_units(self, x_unit, y_unit):
        self.K.unit = y_unit
        self.Gamma1.unit = u.dimensionless_unscaled
        self.E_break1.unit = x_unit
        self.Gamma2.unit = u.dimensionless_unscaled
        self.E_break2.unit = x_unit
        self.Gamma3.unit = u.dimensionless_unscaled

    def evaluate(self, x, K, Gamma1, E_break1, Gamma2, E_break2, Gamma3):
        # Define the three segments of the broken power law
        segment1 = K * x**(-Gamma1) * (x <= E_break1)
        segment2 = (
            K
            * E_break1 ** (Gamma2 - Gamma1)
            * x**(-Gamma2)
            * (x > E_break1)
            * (x <= E_break2)
        )
        segment3 = (
            K
            * E_break1 ** (Gamma2 - Gamma1)
            * E_break2 ** (Gamma3 - Gamma2)
            * x**(-Gamma3)
            * (x > E_break2)
        )
        return segment1 + segment2 + segment3

# Instantiate the expfac component
expfac = ExpFac()

# Instantiate the bkn2pow component
bkn2pow = Bkn2Pow()

# Combine the components into a single model
spectral_model_Particle_Background = 
    constant
    * (
        gaussians[0]
        + gaussians[1]
        + gaussians[2]
        + gaussians[3]
        + gaussians[4]
        + gaussians[5]
        + gaussians[6]
        + gaussians[7]
        + gaussians[8]
        + gaussians[9]
        + gaussians[10]
        + gaussians[11]
        + gaussians[12]
        + gaussians[13]
    
    + expfac * (bkn2pow + powerlaw1 + powerlaw2)
)

combined_model =  spectral_model_Particle_Background + spectral_model1

# Create a point source with the spectral model
ModelPlusParticleBackground = PointSource("source", 0, 0, spectral_shape=combined_model)

# Create the final model
model_combined = Model(ModelPlusParticleBackground)

# Display the model
model_combined.display(complete=True)

Model summary:
==============

                  N
Point sources     1
Extended sources  0
Particle sources  0

Free parameters (63):
--------------------

                                        value min_value max_value  \
source.spectrum.main.composite.k_1        0.0      None      None
source.spectrum.main.composite.F_2        1.0      None      None
source.spectrum.main.composite.mu_2       0.0      None      None
source.spectrum.main.composite.sigma_2    1.0       0.0      None
source.spectrum.main.composite.F_3        1.0      None      None
...                                       ...       ...       ...
source.spectrum.main.composite.kT_21      1.0      0.08      64.0
source.spectrum.main.composite.K_22       1.0       0.0    1000.0
source.spectrum.main.composite.index_22 -2.01     -10.0      10.0
source.spectrum.main.composite.K_23       1.0       0.0    1000.0
source.spectrum.main.composite.kT_23      1.0      0.08      64.0

                                                   unit
source.spectrum.main.composite.k_1       keV-1 s-1 cm-2
source.spectrum.main.composite.F_2             s-1 cm-2
source.spectrum.main.composite.mu_2                 keV
source.spectrum.main.composite.sigma_2              keV
source.spectrum.main.composite.F_3             s-1 cm-2
...                                                 ...
source.spectrum.main.composite.kT_21                keV
source.spectrum.main.composite.K_22      keV-1 s-1 cm-2
source.spectrum.main.composite.index_22
source.spectrum.main.composite.K_23      keV-1 s-1 cm-2
source.spectrum.main.composite.kT_23                keV

[63 rows x 4 columns]

Fixed parameters (10):
---------------------

                                        value min_value max_value unit
source.position.ra                        0.0       0.0     360.0  deg
source.position.dec                       0.0     -90.0      90.0  deg
source.spectrum.main.composite.piv_18     1.0      None      None  keV
source.spectrum.main.composite.piv_19     1.0      None      None  keV
source...redshift_20                      0.0       0.0      15.0
source.spectrum.main.composite.abund_21   1.0       0.0       5.0
source...redshift_21                      0.0       0.0      10.0
source.spectrum.main.composite.piv_22     1.0      None      None  keV
source.spectrum.main.composite.abund_23   1.0       0.0       5.0
source...redshift_23                      0.0       0.0      10.0

Properties (3):
--------------------

                            value  \
source...abundance_table_20  WILM
source...abundance_table_21  AG89
source...abundance_table_23  AG89

                                                              allowed values
source...abundance_table_20                               [WILM, AG89, ASPL]
source...abundance_table_21  [Allen, AG89, GA88, Feldman, GA10, Lodd09, AE8]
source...abundance_table_23  [Allen, AG89, GA88, Feldman, GA10, Lodd09, AE8]

Linked parameters (0):
----------------------

(none)

Independent variables:
----------------------

(none)

Linked functions (0):
----------------------

(none)

In [7]:

# Assign parameter values from the file

# Assign parameters to the constant component
model_combined.source.spectrum.main.composite.k_1.value = parameters[0][0]  # value of the constant factor
model_combined.source.spectrum.main.composite.k_1.delta = parameters[0][1]  # fit delta
model_combined.source.spectrum.main.composite.k_1.bounds = (parameters[0][2], parameters[0][5])  # min and max
model_combined.source.spectrum.main.composite.k_1.free = False  # fixed parameter
# Assign parameters to the Gaussian components
for i in range(14):  # 14 Gaussian components
    model_combined.source.spectrum.main.composite[f"mu_{i+2}"].value = parameters[1 + i * 3][0]  # mu_i
    model_combined.source.spectrum.main.composite[f"mu_{i+2}"].bounds = (parameters[1 + i * 3][2], parameters[1 + i * 3][5])

    model_combined.source.spectrum.main.composite[f"sigma_{i+2}"].bounds = (parameters[2 + i * 3][2], parameters[2 + i * 3][5])
    model_combined.source.spectrum.main.composite[f"sigma_{i+2}"].value = parameters[2 + i * 3][0]  # sigma_i
    model_combined.source.spectrum.main.composite[f"sigma_{i+2}"].free = False  # fixed parameter

    model_combined.source.spectrum.main.composite[f"F_{i+2}"].value = parameters[3 + i * 3][0]  # F_i
    model_combined.source.spectrum.main.composite[f"F_{i+2}"].bounds = (parameters[3 + i * 3][2], parameters[3 + i * 3][5])

# Assign parameters to the expfac component
model_combined.source.spectrum.main.composite.A_16.value = parameters[-13][0]  # A_16
model_combined.source.spectrum.main.composite.A_16.bounds = (parameters[-13][2], parameters[-13][5])

model_combined.source.spectrum.main.composite.f_16.value = parameters[-12][0]  # f_16
model_combined.source.spectrum.main.composite.f_16.bounds = (parameters[-12][2], parameters[-12][5])

model_combined.source.spectrum.main.composite.E_c_16.value = parameters[-11][0]  # E_c_16
model_combined.source.spectrum.main.composite.E_c_16.bounds = (parameters[-11][2], parameters[-11][5])

# Assign parameters to the broken power law (bkn2pow)

model_combined.source.spectrum.main.composite.Gamma1_17.value = parameters[-10][0] # Gamma1_17
model_combined.source.spectrum.main.composite.Gamma1_17.bounds = (parameters[-10][2], parameters[-10][5])


model_combined.source.spectrum.main.composite.E_break1_17.value = parameters[-9][0] # E_break1_17
model_combined.source.spectrum.main.composite.E_break1_17.bounds = (parameters[-9][2], parameters[-9][5])


model_combined.source.spectrum.main.composite.Gamma2_17.value = parameters[-8][0] # Gamma2_17
model_combined.source.spectrum.main.composite.Gamma2_17.bounds = (parameters[-8][2], parameters[-8][5])


model_combined.source.spectrum.main.composite.E_break2_17.value = parameters[-7][0] # E_break2_17
model_combined.source.spectrum.main.composite.E_break2_17.bounds = (parameters[-7][2], parameters[-7][5])


model_combined.source.spectrum.main.composite.Gamma3_17.value = parameters[-6][0] # Gamma3_17
model_combined.source.spectrum.main.composite.Gamma3_17.bounds = (parameters[-6][2], parameters[-6][5])


model_combined.source.spectrum.main.composite.K_17.bounds = (parameters[-5][2], parameters[-5][5])
model_combined.source.spectrum.main.composite.K_17.value = parameters[-5][0]  # K_17

# Assign parameters to the first power law (powerlaw1)
model_combined.source.spectrum.main.composite.index_18.bounds = (parameters[-4][2], parameters[-4][5])
model_combined.source.spectrum.main.composite.index_18.value = parameters[-4][0]  # index_18

model_combined.source.spectrum.main.composite.K_18.bounds = (1e-20, parameters[-3][5])
model_combined.source.spectrum.main.composite.K_18.value = parameters[-3][0]  # K_18

# Assign parameters to the second power law (powerlaw2)
model_combined.source.spectrum.main.composite.index_19.bounds = (parameters[-2][2], parameters[-2][5])
model_combined.source.spectrum.main.composite.index_19.value = parameters[-2][0]  # index_19

model_combined.source.spectrum.main.composite.K_19.bounds = (1e-20, parameters[-1][5])
model_combined.source.spectrum.main.composite.K_19.value = 1e-20  # K_19

###################################################################################################################################################
###################################################################################################################################################
# We set the parameters of the APEC model and the Powerlaw ****Check with Marco's*** 

model_combined.source.spectrum.main.composite.NH_20 = 4.5e-2
model_combined.source.spectrum.main.composite.NH_20.free = True

# model.APEC.spectrum.main.composite.NH_1 = 4.5e-2 

model_combined.source.spectrum.main.composite.index_22.value = 1.46
model_combined.source.spectrum.main.composite.index_22.free = True



model_combined.source.spectrum.main.composite.kT_21.value = 0.2
model_combined.source.spectrum.main.composite.kT_21.free = True
model_combined.source.spectrum.main.composite.abund_21.value = 1.
model_combined.source.spectrum.main.composite.abund_21.free = False



model_combined.source.spectrum.main.composite.kT_23.value = 0.1
model_combined.source.spectrum.main.composite.kT_23.free = True
model_combined.source.spectrum.main.composite.abund_23.value = 1.
model_combined.source.spectrum.main.composite.abund_23.free = False

###################################################################################################################################################
###################################################################################################################################################

model_combined.display(complete=True)

21:01:56 WARNING   We have set the min_value of source.spectrum.main.composite.K_18 to 1e-99       ]8;id=120762;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/astromodels/core/parameter.py\parameter.py]8;;\:]8;id=689561;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/astromodels/core/parameter.py#704\704]8;;\
                  because there was a postive transform

         WARNING   We have set the min_value of source.spectrum.main.composite.K_19 to 1e-99       ]8;id=947836;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/astromodels/core/parameter.py\parameter.py]8;;\:]8;id=536180;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/astromodels/core/parameter.py#704\704]8;;\
                  because there was a postive transform

Model summary:
==============

                  N
Point sources     1
Extended sources  0
Particle sources  0

Free parameters (48):
--------------------

                                             value min_value  \
source.spectrum.main.composite.F_2        0.001795       0.0
source.spectrum.main.composite.mu_2        9.57069      9.45
source.spectrum.main.composite.F_3             0.0       0.0
source.spectrum.main.composite.mu_3        9.10159       8.8
source.spectrum.main.composite.F_4         0.00097       0.0
source.spectrum.main.composite.mu_4        8.19841      8.15
source.spectrum.main.composite.F_5        0.006867       0.0
source.spectrum.main.composite.mu_5        8.59208      7.45
source.spectrum.main.composite.F_6        0.002601       0.0
source.spectrum.main.composite.mu_6        8.03566       7.8
source.spectrum.main.composite.F_7         0.00374       0.0
source.spectrum.main.composite.mu_7        7.44653       7.2
source.spectrum.main.composite.F_8        0.002479       0.0
source.spectrum.main.composite.mu_8        7.02454       6.9
source.spectrum.main.composite.F_9        0.001842       0.0
source.spectrum.main.composite.mu_9        6.89974       6.8
source.spectrum.main.composite.F_10        0.01418       0.0
source.spectrum.main.composite.mu_10       6.38301       6.2
source.spectrum.main.composite.F_11       0.002771       0.0
source.spectrum.main.composite.mu_11       5.87841       5.7
source.spectrum.main.composite.F_12       0.001567       0.0
source.spectrum.main.composite.mu_12       5.38372       5.3
source.spectrum.main.composite.F_13       0.000282       0.0
source.spectrum.main.composite.mu_13       4.52006      4.49
source.spectrum.main.composite.F_14       0.001548       0.0
source.spectrum.main.composite.mu_14       3.66144       3.6
source.spectrum.main.composite.F_15       0.011762       0.0
source.spectrum.main.composite.mu_15       1.47994      1.47
source.spectrum.main.composite.A_16           -0.0      -2.0
source.spectrum.main.composite.f_16       -2.07954      -4.0
source.spectrum.main.composite.E_c_16         0.05       0.0
source.spectrum.main.composite.K_17       0.228888       0.0
source.spectrum.main.composite.Gamma1_17  0.060535      -3.0
source...E_break1_17                       3.62852       0.0
source.spectrum.main.composite.Gamma2_17  0.142454      -3.0
source...E_break2_17                       9.13472       0.0
source.spectrum.main.composite.Gamma3_17   6.54932      -3.0
source.spectrum.main.composite.K_18       0.016829       0.0
source.spectrum.main.composite.index_18    2.16585      -3.0
source.spectrum.main.composite.K_19            0.0       0.0
source.spectrum.main.composite.index_19        6.0      -3.0
source.spectrum.main.composite.NH_20         0.045    0.0001
source.spectrum.main.composite.K_21            1.0       0.0
source.spectrum.main.composite.kT_21           0.2      0.08
source.spectrum.main.composite.K_22            1.0       0.0
source.spectrum.main.composite.index_22       1.46     -10.0
source.spectrum.main.composite.K_23            1.0       0.0
source.spectrum.main.composite.kT_23           0.1      0.08

                                                           max_value  \
source.spectrum.main.composite.F_2        999999999999999983222784.0
source.spectrum.main.composite.mu_2                              9.8
source.spectrum.main.composite.F_3        999999999999999983222784.0
source.spectrum.main.composite.mu_3                             9.15
source.spectrum.main.composite.F_4        999999999999999983222784.0
source.spectrum.main.composite.mu_4                             8.35
source.spectrum.main.composite.F_5        999999999999999983222784.0
source.spectrum.main.composite.mu_5                             8.75
source.spectrum.main.composite.F_6        999999999999999983222784.0
source.spectrum.main.composite.mu_6                             8.15
source.spectrum.main.composite.F_7        999999999999999983222784.0
source.spectrum.main.composite.mu_7                              7.6
source.spectrum.main.composite.F_8        999999999999999983222784.0
source.spectrum.main.composite.mu_8                              7.2
source.spectrum.main.composite.F_9        999999999999999983222784.0
source.spectrum.main.composite.mu_9                              7.1
source.spectrum.main.composite.F_10       999999999999999983222784.0
source.spectrum.main.composite.mu_10                             6.6
source.spectrum.main.composite.F_11       999999999999999983222784.0
source.spectrum.main.composite.mu_11                             6.0
source.spectrum.main.composite.F_12       999999999999999983222784.0
source.spectrum.main.composite.mu_12                             5.6
source.spectrum.main.composite.F_13       999999999999999983222784.0
source.spectrum.main.composite.mu_13                            4.53
source.spectrum.main.composite.F_14       999999999999999983222784.0
source.spectrum.main.composite.mu_14                             3.8
source.spectrum.main.composite.F_15       999999999999999983222784.0
source.spectrum.main.composite.mu_15                             1.5
source.spectrum.main.composite.A_16                              2.0
source.spectrum.main.composite.f_16                              4.0
source.spectrum.main.composite.E_c_16                      1000000.0
source.spectrum.main.composite.K_17       999999999999999983222784.0
source.spectrum.main.composite.Gamma1_17                        10.0
source...E_break1_17                                       1000000.0
source.spectrum.main.composite.Gamma2_17                        10.0
source...E_break2_17                                       1000000.0
source.spectrum.main.composite.Gamma3_17                        10.0
source.spectrum.main.composite.K_18       999999999999999983222784.0
source.spectrum.main.composite.index_18                         10.0
source.spectrum.main.composite.K_19       999999999999999983222784.0
source.spectrum.main.composite.index_19                         10.0
source.spectrum.main.composite.NH_20                         10000.0
source.spectrum.main.composite.K_21                           1000.0
source.spectrum.main.composite.kT_21                            64.0
source.spectrum.main.composite.K_22                           1000.0
source.spectrum.main.composite.index_22                         10.0
source.spectrum.main.composite.K_23                           1000.0
source.spectrum.main.composite.kT_23                            64.0

                                                    unit
source.spectrum.main.composite.F_2              s-1 cm-2
source.spectrum.main.composite.mu_2                  keV
source.spectrum.main.composite.F_3              s-1 cm-2
source.spectrum.main.composite.mu_3                  keV
source.spectrum.main.composite.F_4              s-1 cm-2
source.spectrum.main.composite.mu_4                  keV
source.spectrum.main.composite.F_5              s-1 cm-2
source.spectrum.main.composite.mu_5                  keV
source.spectrum.main.composite.F_6              s-1 cm-2
source.spectrum.main.composite.mu_6                  keV
source.spectrum.main.composite.F_7              s-1 cm-2
source.spectrum.main.composite.mu_7                  keV
source.spectrum.main.composite.F_8              s-1 cm-2
source.spectrum.main.composite.mu_8                  keV
source.spectrum.main.composite.F_9              s-1 cm-2
source.spectrum.main.composite.mu_9                  keV
source.spectrum.main.composite.F_10             s-1 cm-2
source.spectrum.main.composite.mu_10                 keV
source.spectrum.main.composite.F_11             s-1 cm-2
source.spectrum.main.composite.mu_11                 keV
source.spectrum.main.composite.F_12             s-1 cm-2
source.spectrum.main.composite.mu_12                 keV
source.spectrum.main.composite.F_13             s-1 cm-2
source.spectrum.main.composite.mu_13                 keV
source.spectrum.main.composite.F_14             s-1 cm-2
source.spectrum.main.composite.mu_14                 keV
source.spectrum.main.composite.F_15             s-1 cm-2
source.spectrum.main.composite.mu_15                 keV
source.spectrum.main.composite.A_16       keV-1 s-1 cm-2
source.spectrum.main.composite.f_16                keV-1
source.spectrum.main.composite.E_c_16                keV
source.spectrum.main.composite.K_17       keV-1 s-1 cm-2
source.spectrum.main.composite.Gamma1_17
source...E_break1_17                                 keV
source.spectrum.main.composite.Gamma2_17
source...E_break2_17                                 keV
source.spectrum.main.composite.Gamma3_17
source.spectrum.main.composite.K_18       keV-1 s-1 cm-2
source.spectrum.main.composite.index_18
source.spectrum.main.composite.K_19       keV-1 s-1 cm-2
source.spectrum.main.composite.index_19
source.spectrum.main.composite.NH_20                cm-2
source.spectrum.main.composite.K_21       keV-1 s-1 cm-2
source.spectrum.main.composite.kT_21                 keV
source.spectrum.main.composite.K_22       keV-1 s-1 cm-2
source.spectrum.main.composite.index_22
source.spectrum.main.composite.K_23       keV-1 s-1 cm-2
source.spectrum.main.composite.kT_23                 keV

Fixed parameters (25):
---------------------

                                          value min_value max_value  \
source.position.ra                          0.0       0.0     360.0
source.position.dec                         0.0     -90.0      90.0
source.spectrum.main.composite.k_1          1.0       0.0      10.0
source.spectrum.main.composite.sigma_2   0.0001       0.0      20.0
source.spectrum.main.composite.sigma_3   0.0001       0.0      20.0
source.spectrum.main.composite.sigma_4   0.0001       0.0      20.0
source.spectrum.main.composite.sigma_5   0.0001       0.0      20.0
source.spectrum.main.composite.sigma_6   0.0001       0.0      20.0
source.spectrum.main.composite.sigma_7   0.0001       0.0      20.0
source.spectrum.main.composite.sigma_8   0.0001       0.0      20.0
source.spectrum.main.composite.sigma_9   0.0001       0.0      20.0
source.spectrum.main.composite.sigma_10  0.0001       0.0      20.0
source.spectrum.main.composite.sigma_11  0.0001       0.0      20.0
source.spectrum.main.composite.sigma_12  0.0001       0.0      20.0
source.spectrum.main.composite.sigma_13  0.0001       0.0      20.0
source.spectrum.main.composite.sigma_14  0.0001       0.0      20.0
source.spectrum.main.composite.sigma_15  0.0001       0.0      20.0
source.spectrum.main.composite.piv_18       1.0      None      None
source.spectrum.main.composite.piv_19       1.0      None      None
source...redshift_20                        0.0       0.0      15.0
source.spectrum.main.composite.abund_21     1.0       0.0       5.0
source...redshift_21                        0.0       0.0      10.0
source.spectrum.main.composite.piv_22       1.0      None      None
source.spectrum.main.composite.abund_23     1.0       0.0       5.0
source...redshift_23                        0.0       0.0      10.0

                                                   unit
source.position.ra                                  deg
source.position.dec                                 deg
source.spectrum.main.composite.k_1       keV-1 s-1 cm-2
source.spectrum.main.composite.sigma_2              keV
source.spectrum.main.composite.sigma_3              keV
source.spectrum.main.composite.sigma_4              keV
source.spectrum.main.composite.sigma_5              keV
source.spectrum.main.composite.sigma_6              keV
source.spectrum.main.composite.sigma_7              keV
source.spectrum.main.composite.sigma_8              keV
source.spectrum.main.composite.sigma_9              keV
source.spectrum.main.composite.sigma_10             keV
source.spectrum.main.composite.sigma_11             keV
source.spectrum.main.composite.sigma_12             keV
source.spectrum.main.composite.sigma_13             keV
source.spectrum.main.composite.sigma_14             keV
source.spectrum.main.composite.sigma_15             keV
source.spectrum.main.composite.piv_18               keV
source.spectrum.main.composite.piv_19               keV
source...redshift_20
source.spectrum.main.composite.abund_21
source...redshift_21
source.spectrum.main.composite.piv_22               keV
source.spectrum.main.composite.abund_23
source...redshift_23

Properties (3):
--------------------

                            value  \
source...abundance_table_20  WILM
source...abundance_table_21  AG89
source...abundance_table_23  AG89

                                                              allowed values
source...abundance_table_20                               [WILM, AG89, ASPL]
source...abundance_table_21  [Allen, AG89, GA88, Feldman, GA10, Lodd09, AE8]
source...abundance_table_23  [Allen, AG89, GA88, Feldman, GA10, Lodd09, AE8]

Linked parameters (0):
----------------------

(none)

Independent variables:
----------------------

(none)

Linked functions (0):
----------------------

(none)

In [8]:
ogip = OGIPLike("ogip", observation=LMC1halfdeg_pha, response=LMC1halfdeg_rmf,  arf_file=LMC1halfdeg_arf)

ogip.set_active_measurements("0.3-9.5")


#***********************************************************************************************************************




jl = JointLikelihood(model_combined,DataList(ogip))

result = jl.fit()


fig = display_spectrum_model_counts(jl,data_color='blue',model_color='red')

fig.set_size_inches(13,10)

ax = fig.get_axes()[0]

ax.set_xlim(left=0.2,right=11)
ax.set_xlabel('Energy [keV]',fontsize=28)
ax.set_ylabel('Rate [counts s$^{-1}$ keV$^{-1}$]',fontsize=28)
ax.set_xscale('log')
ax.set_yscale('log')

21:37:36 WARNING   Could not find QUALITY in columns or header of PHA file. This is not a valid ]8;id=376361;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/utils/spectrum/pha_spectrum.py\pha_spectrum.py]8;;\:]8;id=377275;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/utils/spectrum/pha_spectrum.py#219\219]8;;\
                  OGIP file. Assuming QUALITY =0 (good)

         WARNING   Found TSTOP and TELAPSE. This file is invalid. Using TSTOP.                  ]8;id=703909;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/utils/spectrum/pha_spectrum.py\pha_spectrum.py]8;;\:]8;id=494242;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/utils/spectrum/pha_spectrum.py#274\274]8;;\

         INFO      Auto-probed noise models:                                                    ]8;id=239599;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/plugins/SpectrumLike.py\SpectrumLike.py]8;;\:]8;id=305885;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/plugins/SpectrumLike.py#490\490]8;;\

         INFO      - observation: poisson                                                       ]8;id=513296;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/plugins/SpectrumLike.py\SpectrumLike.py]8;;\:]8;id=811306;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/plugins/SpectrumLike.py#491\491]8;;\

         INFO      - background: None                                                           ]8;id=495431;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/plugins/SpectrumLike.py\SpectrumLike.py]8;;\:]8;id=208507;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/plugins/SpectrumLike.py#492\492]8;;\

         INFO      Range 0.3-9.5 translates to channels 38-895                                 ]8;id=350755;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/plugins/SpectrumLike.py\SpectrumLike.py]8;;\:]8;id=288913;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/plugins/SpectrumLike.py#1247\1247]8;;\

         INFO      set the minimizer to minuit                                             ]8;id=912352;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=869804;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1046\1046]8;;\

21:38:26 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=869231;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=162095;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02454000e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38301000e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=384120;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=262904;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02454000e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38301000e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:38:40 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=892491;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=824891;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38301000e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:38:56 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=781165;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=975715;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=665749;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=347485;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:01 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=84229;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=207765;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=689062;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=843990;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -1.52940262e-08 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=135072;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=49488;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -9.23698610e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:02 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=229180;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=16794;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -2.70673978e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=502956;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=168842;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -2.85816578e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:03 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=527329;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=372968;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.00959178e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 5.47232686e+19             ]8;id=906969;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=794745;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 2.96418540e+19             ]8;id=999073;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=877756;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=575618;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=291546;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57160579e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=424930;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=666434;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57143916e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=890802;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=574495;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57153080e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=978620;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=276604;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57151414e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=654316;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=565904;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  6.16777447e+22  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:04 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=327538;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=668209;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  6.07413673e+22  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=794148;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=986020;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.14402233e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=795708;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=616703;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.02816402e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=134697;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=52129;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    6.16777447e+22  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=205639;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=153069;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    6.07413673e+22  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=477859;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=576992;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.24579545e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=160111;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=287778;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.16365558e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:05 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=972417;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=375785;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.60263209e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=380988;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=271583;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.47107503e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=411525;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=10427;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241169e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=775794;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=641031;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241134e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=131685;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=334823;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241215e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=426970;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=145169;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241088e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=160314;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=371024;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.58036839e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:06 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=950060;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=616654;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.49321144e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=986654;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=893485;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566010e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=420690;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=465821;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03565990e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=591425;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=700408;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566027e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=271638;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=404900;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03565973e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=999864;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=983112;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  6.16777447e+22  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=433434;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=130570;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  6.07413673e+22  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=100117;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=105941;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.53408799e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:07 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=436082;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=693334;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.34757985e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=99106;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=62534;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    5.73659663e+18  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=989028;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=765324;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    1.95361004e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=717747;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=844408;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02824316e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=492142;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=967709;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.01353520e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=639044;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=844598;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  6.16777447e+22  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=554699;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=548229;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  6.07413673e+22  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:08 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=147580;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=254933;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.97364951e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=842334;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=202862;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.83813589e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=702412;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=68030;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.56564566e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=904437;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=230688;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.50787834e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=501806;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=452979;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.58437126e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=748624;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=334480;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.48922765e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:09 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=54854;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=115330;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273196e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=367198;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=880948;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273171e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=316852;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=401166;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273221e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=148612;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=565217;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273147e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=790629;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=820826;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.54404702e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=499443;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=277866;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.52943604e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=735483;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=526944;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841002e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:10 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=729381;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=169891;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87840998e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=262085;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=877492;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    2.22497005e+19  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=777875;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=74406;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    7.63885462e+18  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=141074;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=742495;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    1.47235500e+21  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=717258;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=555661;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    1.32638142e+21  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=513347;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=776181;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38378729e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:11 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=934076;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=244556;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38365273e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=297862;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=573777;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372673e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=308663;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=640455;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38371327e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=274609;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=213140;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.54404702e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=334368;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=976244;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.52943604e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=25168;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=262348;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006002e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=869744;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=398150;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52005998e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:12 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=89634;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=740130;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006001e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=800442;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=402030;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52005999e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=544354;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=611354;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.54404702e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=261948;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=711990;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.52943604e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=569057;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=163463;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144002e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=261081;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=314935;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66143998e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:13 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=357671;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=976836;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  6.16777447e+22  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=555592;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=481610;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  6.07413673e+22  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=64695;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=114020;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.48065207e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=676456;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=733098;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47924058e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=740515;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=715900;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.48502797e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=93817;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=616755;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47545160e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=569744;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=662273;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -2.87709403e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:14 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=202806;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=758842;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.48279804e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=871969;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=457665;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07866490e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=751544;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=285282;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.08041497e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=463234;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=60599;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07936257e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=228955;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=466293;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07971742e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:15 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=593426;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=605200;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  6.81454519e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=941944;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=430019;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  3.46580613e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=306004;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=769935;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  3.57612590e-01  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=922386;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=664170;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  2.27387153e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=558339;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=160440;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.54404702e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=528764;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=937384;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.52943604e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:16 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=830822;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=12634;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.06657015e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=552450;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=338572;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.04037004e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=206565;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=663159;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05478001e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=135398;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=936619;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05216000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=333997;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=183776;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.63048530e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:17 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=203621;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=1027;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62655523e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=155572;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=408175;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.43088675e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=303955;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=737831;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.41819369e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=201735;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=413134;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42517466e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=443685;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=247648;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42390535e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:18 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=276026;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=871190;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13697521e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=279306;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=918474;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13246506e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=994873;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=725228;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.14092363e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=771383;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=596539;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.12851847e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=71207;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=258767;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.60411308e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:19 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=215437;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=307435;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.49424766e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=5987;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=410562;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.55481196e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=846633;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=491960;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54382525e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=794244;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=140115;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -6.85990193e-01  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=122400;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=814496;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -2.85247576e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:20 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=62032;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=526840;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.11631806e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=683789;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=230883;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -2.42812379e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=467878;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=431495;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  5.37909009e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=169522;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=265334;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00 -7.20743643e-01 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:21 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=929897;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=253124;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.72861792e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=709810;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=26893;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.73273798e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=134639;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=941113;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    8.57050964e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=398190;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=736807;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    2.81740317e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=482659;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=842994;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00  6.23816244e-01  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:22 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=388356;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=667356;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -2.98765067e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=718815;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=486210;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.89559460e+00  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=213389;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=926914;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00 -6.20086543e+00  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=663649;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=42068;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  5.42431666e+00
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=249005;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=116626;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.77122580e+00
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:23 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=163548;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=476064;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    4.57272547e-01  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=763045;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=392355;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                   -4.91015516e-01  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=34912;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=808578;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.89559460e+00  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:24 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=487322;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=69825;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                   -6.20086543e+00  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=58530;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=557477;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.95261160e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=338877;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=150978;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  9.63739160e-01  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=250438;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=674178;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  6.02415351e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=875293;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=736314;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16 -3.46161243e+00  2.70616862e-16  1.00000000e-01]

21:39:25 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=138179;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=836733;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.89559460e+00  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=362602;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=444173;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00 -6.20086543e+00  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=548314;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=211473;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  4.55199713e+00]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=256185;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=533345;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  3.46802882e+00]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=7162;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=545645;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 5.47232686e+19             ]8;id=758395;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=733024;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:26 WARNING   These parameters returned a logLike = Nan: [ 2.96418540e+19             ]8;id=594824;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=766450;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 4.24330204e+21             ]8;id=892823;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=23816;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 3.99316985e+21             ]8;id=799588;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=489428;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 6.41053138e+22             ]8;id=346474;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=511313;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 6.31518432e+22             ]8;id=80654;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=607698;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=836890;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=626187;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:27 WARNING   These parameters returned a logLike = Nan: [ 9.60993495e+17             ]8;id=369204;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=206438;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=125746;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=711323;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152272e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=254649;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=491268;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.60993495e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=696676;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=849632;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159047e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:28 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=733637;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=801858;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.60993495e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=355183;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=990745;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841022e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=458740;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=71320;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.60993495e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=920660;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=977148;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241325e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=470841;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=228210;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.60993495e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:29 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=39710;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=955977;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566028e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=951785;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=473974;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.60993495e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=119145;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=624559;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653022e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=737811;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=288385;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.60993495e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=216742;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=805823;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085289e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:30 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=493434;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=732583;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.60993495e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=365170;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=298773;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974023e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=703210;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=45914;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.60993495e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=362877;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=686435;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273192e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=269885;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=887781;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.60993495e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:31 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=855423;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=241034;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841013e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=121329;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=990106;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.60993495e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=291812;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=902461;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372029e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=225487;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=307436;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.60993495e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=169385;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=207417;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006004e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:32 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=382791;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=142272;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.60993495e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=418467;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=834007;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144017e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=600018;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=550413;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.60993495e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=906561;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=422921;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994002e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=602961;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=949219;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17936244e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:33 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=139366;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=904488;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07953109e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=805276;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=718110;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.16883871e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=621212;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=100500;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.60993495e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=255977;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=459034;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05493646e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=546844;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=856181;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.64276705e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=253744;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=386181;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42468406e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:34 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=619080;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=917739;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.15728468e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=125279;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=413618;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54933337e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=155422;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=986131;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77393161e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=1902;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=132275;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585627e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=40786;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=543839;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999577e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=349527;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=309382;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00001130e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:35 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=147312;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=203014;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678132e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=216559;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=249301;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  4.33475920e-05  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=298627;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=919510;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00019582e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=204275;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=466191;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    4.33475920e-05  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:36 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=773267;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=945643;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000691e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=929080;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=515355;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  4.33475920e-05  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=6887;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=354533;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00008278e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53978433e+17             ]8;id=231417;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=137342;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152248e+00  9.53978433e+17  9.10159002e+00
                    9.53978433e+17  8.19841001e+00  9.53978433e+17  8.59241158e+00
                    9.53978433e+17  8.03566001e+00  9.53978433e+17  7.44653001e+00
                    9.53978433e+17  7.02085276e+00  9.53978433e+17  6.89974001e+00
                    9.53978433e+17  6.38273184e+00  9.53978433e+17  5.87841001e+00
                    9.53978433e+17  5.38372001e+00  9.53978433e+17  4.52006000e+00
                    9.53978433e+17  3.66144001e+00  9.53978433e+17  1.47994000e+00
                   -3.17992172e-09 -2.07953963e+00  5.00697897e-02  9.53978433e+17
                    6.05353110e-02  3.62911307e+00  1.42454600e-01  9.13565964e+00
                    6.54932056e+00 -1.77394869e+00  2.16585026e+00 -1.99999580e+01
                    6.00000047e+00 -1.34678723e+00  1.80615531e-06  2.00000816e-01
                    1.80615531e-06  1.46000029e+00  1.80615531e-06  1.00000345e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.54130661e+17             ]8;id=954125;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=990275;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152249e+00  9.54130661e+17  9.10159003e+00
                    9.54130661e+17  8.19841001e+00  9.54130661e+17  8.59241162e+00
                    9.54130661e+17  8.03566002e+00  9.54130661e+17  7.44653001e+00
                    9.54130661e+17  7.02085276e+00  9.54130661e+17  6.89974001e+00
                    9.54130661e+17  6.38273184e+00  9.54130661e+17  5.87841001e+00
                    9.54130661e+17  5.38372002e+00  9.54130661e+17  4.52006000e+00
                    9.54130661e+17  3.66144001e+00  9.54130661e+17  1.47994000e+00
                   -3.17990956e-09 -2.07953944e+00  5.01047029e-02  9.54130661e+17
                    6.05356165e-02  3.62940962e+00  1.42454900e-01  9.13612948e+00
                    6.54932084e+00 -1.77394832e+00  2.16585039e+00 -1.99999580e+01
                    6.00000071e+00 -1.34678710e+00  2.70923278e-06  2.00001224e-01
                    2.70923278e-06  1.46000043e+00  2.70923278e-06  1.00000517e-01]

21:39:37 WARNING   These parameters returned a logLike = Nan: [ 9.53826217e+17             ]8;id=450720;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=41733;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152248e+00  9.53826217e+17  9.10159001e+00
                    9.53826217e+17  8.19841000e+00  9.53826217e+17  8.59241155e+00
                    9.53826217e+17  8.03566001e+00  9.53826217e+17  7.44653000e+00
                    9.53826217e+17  7.02085276e+00  9.53826217e+17  6.89974000e+00
                    9.53826217e+17  6.38273184e+00  9.53826217e+17  5.87841000e+00
                    9.53826217e+17  5.38372001e+00  9.53826217e+17  4.52006000e+00
                    9.53826217e+17  3.66144000e+00  9.53826217e+17  1.47994000e+00
                   -3.17993388e-09 -2.07953981e+00  5.00348888e-02  9.53826217e+17
                    6.05350055e-02  3.62881653e+00  1.42454300e-01  9.13518981e+00
                    6.54932028e+00 -1.77394906e+00  2.16585013e+00 -1.99999580e+01
                    6.00000024e+00 -1.34678736e+00  9.03077716e-07  2.00000408e-01
                    9.03077716e-07  1.46000014e+00  9.03077716e-07  1.00000172e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=369292;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=626132;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=228979;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=284877;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=742001;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=293690;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=99104;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=726675;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.60993495e+17             ]8;id=315077;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=75127;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=114810;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=630578;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152272e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:38 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=43282;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=164095;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.60993495e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=231223;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=456985;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159047e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=476451;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=544022;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.60993495e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=126359;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=676754;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841022e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=945319;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=518016;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.60993495e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=552582;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=746654;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241325e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=96596;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=683992;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.60993495e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:39 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=686326;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=448944;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566028e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=338030;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=798773;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.60993495e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=745987;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=291318;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653022e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=352885;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=189957;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.60993495e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=765334;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=984569;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085289e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=576384;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=847482;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.60993495e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=358954;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=313151;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974023e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:40 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=987152;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=181124;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.60993495e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=909435;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=632729;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273192e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=8424;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=929399;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.60993495e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=779224;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=537278;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841013e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=298826;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=786857;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.60993495e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:41 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=657464;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=385107;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372029e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=651596;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=739837;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.60993495e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=917748;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=430283;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006004e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=336516;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=41789;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.60993495e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=33514;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=147525;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144017e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:42 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=250874;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=170999;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.60993495e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=55508;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=792489;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994002e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=584857;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=574508;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17936244e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=240492;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=242923;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07953109e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=913148;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=366702;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.16883871e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:43 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=747180;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=411637;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.60993495e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=905067;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=333421;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05493646e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=252025;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=983988;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.64276705e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=42964;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=905846;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42468406e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=814590;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=504928;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.15728468e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:44 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=462679;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=783547;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54933337e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=644658;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=687781;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77393161e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=993634;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=279609;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585627e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=376903;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=836241;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999577e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:45 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=98248;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=358557;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00001130e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=871938;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=924275;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678132e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=793306;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=398529;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  4.33475920e-05  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=200545;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=900909;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00019582e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=944334;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=960369;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    4.33475920e-05  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:46 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=563927;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=888409;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000691e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=587948;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=937461;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  4.33475920e-05  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=473075;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=182004;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00008278e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53978433e+17             ]8;id=240017;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=151684;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152248e+00  9.53978433e+17  9.10159002e+00
                    9.53978433e+17  8.19841001e+00  9.53978433e+17  8.59241158e+00
                    9.53978433e+17  8.03566001e+00  9.53978433e+17  7.44653001e+00
                    9.53978433e+17  7.02085276e+00  9.53978433e+17  6.89974001e+00
                    9.53978433e+17  6.38273184e+00  9.53978433e+17  5.87841001e+00
                    9.53978433e+17  5.38372001e+00  9.53978433e+17  4.52006000e+00
                    9.53978433e+17  3.66144001e+00  9.53978433e+17  1.47994000e+00
                   -3.17992172e-09 -2.07953963e+00  5.00697897e-02  9.53978433e+17
                    6.05353110e-02  3.62911307e+00  1.42454600e-01  9.13565964e+00
                    6.54932056e+00 -1.77394869e+00  2.16585026e+00 -1.99999580e+01
                    6.00000047e+00 -1.34678723e+00  1.80615531e-06  2.00000816e-01
                    1.80615531e-06  1.46000029e+00  1.80615531e-06  1.00000345e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.54130661e+17             ]8;id=495694;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=444232;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152249e+00  9.54130661e+17  9.10159003e+00
                    9.54130661e+17  8.19841001e+00  9.54130661e+17  8.59241162e+00
                    9.54130661e+17  8.03566002e+00  9.54130661e+17  7.44653001e+00
                    9.54130661e+17  7.02085276e+00  9.54130661e+17  6.89974001e+00
                    9.54130661e+17  6.38273184e+00  9.54130661e+17  5.87841001e+00
                    9.54130661e+17  5.38372002e+00  9.54130661e+17  4.52006000e+00
                    9.54130661e+17  3.66144001e+00  9.54130661e+17  1.47994000e+00
                   -3.17990956e-09 -2.07953944e+00  5.01047029e-02  9.54130661e+17
                    6.05356165e-02  3.62940962e+00  1.42454900e-01  9.13612948e+00
                    6.54932084e+00 -1.77394832e+00  2.16585039e+00 -1.99999580e+01
                    6.00000071e+00 -1.34678710e+00  2.70923278e-06  2.00001224e-01
                    2.70923278e-06  1.46000043e+00  2.70923278e-06  1.00000517e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53826217e+17             ]8;id=992552;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=236527;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152248e+00  9.53826217e+17  9.10159001e+00
                    9.53826217e+17  8.19841000e+00  9.53826217e+17  8.59241155e+00
                    9.53826217e+17  8.03566001e+00  9.53826217e+17  7.44653000e+00
                    9.53826217e+17  7.02085276e+00  9.53826217e+17  6.89974000e+00
                    9.53826217e+17  6.38273184e+00  9.53826217e+17  5.87841000e+00
                    9.53826217e+17  5.38372001e+00  9.53826217e+17  4.52006000e+00
                    9.53826217e+17  3.66144000e+00  9.53826217e+17  1.47994000e+00
                   -3.17993388e-09 -2.07953981e+00  5.00348888e-02  9.53826217e+17
                    6.05350055e-02  3.62881653e+00  1.42454300e-01  9.13518981e+00
                    6.54932028e+00 -1.77394906e+00  2.16585013e+00 -1.99999580e+01
                    6.00000024e+00 -1.34678736e+00  9.03077716e-07  2.00000408e-01
                    9.03077716e-07  1.46000014e+00  9.03077716e-07  1.00000172e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=608444;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=17414;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:47 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=381078;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=120741;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=601209;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=282984;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=427896;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=594978;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.60993495e+17             ]8;id=954808;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=235773;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=935030;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=550719;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152272e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=729594;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=898087;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.60993495e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:48 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=581747;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=315156;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159047e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=818975;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=641224;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.60993495e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=683860;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=18155;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841022e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=146961;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=828546;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.60993495e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=455783;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=677837;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241325e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:49 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=560255;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=662596;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.60993495e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=726724;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=25647;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566028e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=20801;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=421151;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.60993495e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=218437;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=142203;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653022e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=956206;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=298012;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.60993495e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=397103;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=464823;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085289e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:50 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=524814;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=628440;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.60993495e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=640929;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=406915;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974023e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=656723;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=509455;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.60993495e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=878758;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=476238;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273192e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=777485;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=982740;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.60993495e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:51 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=545390;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=752270;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841013e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=426399;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=244923;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.60993495e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=900219;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=34778;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372029e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=263015;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=859696;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.60993495e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:52 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=663005;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=555088;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006004e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=641673;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=580868;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.60993495e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=504734;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=481554;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144017e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=857032;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=79128;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.60993495e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=247478;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=506475;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994002e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:53 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=243978;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=955839;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17936244e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=662671;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=247244;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07953109e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=889120;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=952295;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.16883871e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=462206;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=639309;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.60993495e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=624378;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=765673;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05493646e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:54 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=436516;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=880780;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.64276705e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=318151;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=203640;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42468406e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=902999;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=172718;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.15728468e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=510792;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=597533;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54933337e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=361986;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=526737;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77393161e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=935372;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=298166;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585627e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=661167;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=143465;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999577e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:55 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=242681;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=241519;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00001130e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=562826;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=61503;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678132e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=455620;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=546550;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  4.33475920e-05  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=110079;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=924290;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00019582e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=244354;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=711887;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    4.33475920e-05  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:56 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=973391;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=655972;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000691e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=50553;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=184207;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  4.33475920e-05  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=591776;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=252702;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00008278e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53978433e+17             ]8;id=857153;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=825367;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152248e+00  9.53978433e+17  9.10159002e+00
                    9.53978433e+17  8.19841001e+00  9.53978433e+17  8.59241158e+00
                    9.53978433e+17  8.03566001e+00  9.53978433e+17  7.44653001e+00
                    9.53978433e+17  7.02085276e+00  9.53978433e+17  6.89974001e+00
                    9.53978433e+17  6.38273184e+00  9.53978433e+17  5.87841001e+00
                    9.53978433e+17  5.38372001e+00  9.53978433e+17  4.52006000e+00
                    9.53978433e+17  3.66144001e+00  9.53978433e+17  1.47994000e+00
                   -3.17992172e-09 -2.07953963e+00  5.00697897e-02  9.53978433e+17
                    6.05353110e-02  3.62911307e+00  1.42454600e-01  9.13565964e+00
                    6.54932056e+00 -1.77394869e+00  2.16585026e+00 -1.99999580e+01
                    6.00000047e+00 -1.34678723e+00  1.80615531e-06  2.00000816e-01
                    1.80615531e-06  1.46000029e+00  1.80615531e-06  1.00000345e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.54130661e+17             ]8;id=248707;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=477934;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152249e+00  9.54130661e+17  9.10159003e+00
                    9.54130661e+17  8.19841001e+00  9.54130661e+17  8.59241162e+00
                    9.54130661e+17  8.03566002e+00  9.54130661e+17  7.44653001e+00
                    9.54130661e+17  7.02085276e+00  9.54130661e+17  6.89974001e+00
                    9.54130661e+17  6.38273184e+00  9.54130661e+17  5.87841001e+00
                    9.54130661e+17  5.38372002e+00  9.54130661e+17  4.52006000e+00
                    9.54130661e+17  3.66144001e+00  9.54130661e+17  1.47994000e+00
                   -3.17990956e-09 -2.07953944e+00  5.01047029e-02  9.54130661e+17
                    6.05356165e-02  3.62940962e+00  1.42454900e-01  9.13612948e+00
                    6.54932084e+00 -1.77394832e+00  2.16585039e+00 -1.99999580e+01
                    6.00000071e+00 -1.34678710e+00  2.70923278e-06  2.00001224e-01
                    2.70923278e-06  1.46000043e+00  2.70923278e-06  1.00000517e-01]

21:39:57 WARNING   These parameters returned a logLike = Nan: [ 9.53826217e+17             ]8;id=668513;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=461066;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152248e+00  9.53826217e+17  9.10159001e+00
                    9.53826217e+17  8.19841000e+00  9.53826217e+17  8.59241155e+00
                    9.53826217e+17  8.03566001e+00  9.53826217e+17  7.44653000e+00
                    9.53826217e+17  7.02085276e+00  9.53826217e+17  6.89974000e+00
                    9.53826217e+17  6.38273184e+00  9.53826217e+17  5.87841000e+00
                    9.53826217e+17  5.38372001e+00  9.53826217e+17  4.52006000e+00
                    9.53826217e+17  3.66144000e+00  9.53826217e+17  1.47994000e+00
                   -3.17993388e-09 -2.07953981e+00  5.00348888e-02  9.53826217e+17
                    6.05350055e-02  3.62881653e+00  1.42454300e-01  9.13518981e+00
                    6.54932028e+00 -1.77394906e+00  2.16585013e+00 -1.99999580e+01
                    6.00000024e+00 -1.34678736e+00  9.03077716e-07  2.00000408e-01
                    9.03077716e-07  1.46000014e+00  9.03077716e-07  1.00000172e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=198479;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=742151;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=176523;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=702341;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=558027;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=529327;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=182770;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=343024;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.60993495e+17             ]8;id=245824;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=570672;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:58 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=573354;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=976595;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152272e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=783370;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=569554;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.60993495e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=986406;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=586767;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159047e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=605219;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=596581;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.60993495e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=26650;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=362891;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841022e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:39:59 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=123548;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=561907;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.60993495e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=670635;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=91515;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241325e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=793160;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=187179;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.60993495e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=795738;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=677306;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566028e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=768764;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=156547;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.60993495e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:40:00 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=641893;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=498048;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653022e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=234129;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=760871;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.60993495e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=242607;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=391813;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085289e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=266751;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=29020;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.60993495e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=857746;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=578215;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974023e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:40:01 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=676236;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=639106;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.60993495e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=691625;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=576444;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273192e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=956768;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=468882;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.60993495e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=231785;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=268218;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841013e+00
                    9.53674013e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=256817;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=251005;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.60993495e+17  5.38372000e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

21:40:02 WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=109169;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=96072;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372029e+00  9.53674013e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

         WARNING   These parameters returned a logLike = Nan: [ 9.53674013e+17             ]8;id=588207;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py\joint_likelihood.py]8;;\:]8;id=10934;file:///home/jortecal/GitHub/eRosita/.venv/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py#1006\1006]8;;\
                  9.57152247e+00  9.53674013e+17  9.10159000e+00
                    9.53674013e+17  8.19841000e+00  9.53674013e+17  8.59241151e+00
                    9.53674013e+17  8.03566000e+00  9.53674013e+17  7.44653000e+00
                    9.53674013e+17  7.02085275e+00  9.53674013e+17  6.89974000e+00
                    9.53674013e+17  6.38273184e+00  9.53674013e+17  5.87841000e+00
                    9.53674013e+17  5.38372000e+00  9.60993495e+17  4.52006000e+00
                    9.53674013e+17  3.66144000e+00  9.53674013e+17  1.47994000e+00
                   -3.17994603e-09 -2.07954000e+00  5.00000000e-02  9.53674013e+17
                    6.05347000e-02  3.62852000e+00  1.42454000e-01  9.13472000e+00
                    6.54932000e+00 -1.77394943e+00  2.16585000e+00 -1.99999580e+01
                    6.00000000e+00 -1.34678749e+00  2.70616862e-16  2.00000000e-01
                    2.70616862e-16  1.46000000e+00  2.70616862e-16  1.00000000e-01]

KeyboardInterrupt: